### ISSUE TITLE
Doesn't appear to work with macOS Sierra

### ISSUE THREAD

**Issue by dvdgorila** [Fogh/CouchPotato-Alfred#6]
In macOS Sierra typing Couch add movie doesn't work. In fact hitting space after couch add, defaults to a web search. 

Below is a snippet of the error in the debug log

`2017-01-21 20:54:44][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "couchpotatoAlfred.py", line 102, in search_movie
    data = get_data("movie.search" + "?q=" + urllib.quote(query))
  File "couchpotatoAlfred.py", line 61, in get_data
    return json.loads(res.read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`
Can this be updated to work with Sierra?

**Comment by Fogh** [comment]
Maybe the CP API has changed. I haven't used CP in a long time. Since I'm not using CP anymore it is hard for me to fix this issue, so if someone else could make a pull request and fix this, that would be great!
